### ISSUE TITLE
Normalization inside comments

### ISSUE THREAD

**Issue by denji** [slomkowski/nginx-config-formatter#11]
Normalization inside comments is required, if possible, after position alignment.

Input data:
```nginx
http {
    #log_format  main  "......."
    #                  "....";
#                      '....';
     #             "....";
  #                    '....';
}
```

Output result
```nginx
http {
    #log_format  main  "......."
    #                  "....";
    #                      '....'; < unalignment
    #             "...."; < unalignment
    #                    '....'; < unalignment
}
```

**Comment by dandelionred** [comment]
Input
```
        #if (!-f $request_filename) {
            #rewrite ^/static/?(.*)$ /static.php?resource=$1 last;
        #
```
Ouput
```
        #if (!-f $request_filename) {
        #rewrite ^/static/?(.*)$ /static.php?resource=$1 last;
        #}
```
The desired result
```
        #if (!-f $request_filename) {
        #    rewrite ^/static/?(.*)$ /static.php?resource=$1 last;
        #}

```

**Comment by RickieL** [comment]
should the tool to change the comment after the "#" sign?
In my opinion, this is only format tool, should not change the comment content.

**Comment by denji** [comment]
In the context of a comment, there can be more than just plain text.

**Comment by dandelionred** [comment]
> In my opinion, this is only format tool

Exactly. In the example above formatting is destroyed by the tool. I think it is absolutely OK to make changes in the `^\s*#\s*` part for the sake of **formatting**,

**Comment by dandelionred** [comment]
@RickieL I get your point after all. The thing is my example is a self-contained valid config piece and it is obvious to a human's eye how it should be formatted.

Ideally it should examine consecutive commented lines, check if it is a self-contained valid config piece, format it as if it was not commented and comment it out after that. But I guess it is an overkill for the small tool :(
