### ISSUE TITLE
errounous semicolon after single-line location block

### ISSUE THREAD

**Issue by Mic92** [slomkowski/nginx-config-formatter#16]
Reported in https://github.com/NixOS/nixpkgs/pull/57979#issuecomment-480802920:

The following configuration:

```
location /example { allow 192.168.0.0/16; deny all; }
```

results in 

```
  location /example {
    allow 192.168.0.0/16;
    deny all;
  }
  ;

```

the trailing `;` will produce an error message in nginx like this:

```
апр 08 14:55:45 web.elven.pw systemd[1]: Starting Nginx Web Server...
апр 08 14:55:45 web.elven.pw pnzhwc1q1is8vbdkg34ksicqq9jh5chc-unit-script-nginx-pre-start[2430]: nginx: [emerg] unexpected ";" in /nix/store/glvppaxv9gqg9vj179ph9rmj8yg41d72-nginx.conf:151
```

The nginx version is 1.14.2.

**Comment by Mic92** [comment]
Here is a workaround https://github.com/NixOS/nixpkgs/pull/59181
However I would very much prefer a fix in nginx-config-formatter instead.

**Comment by Mic92** [comment]
cc @4z3

**Comment by slomkowski** [comment]
Fixed, will be published in next release.
