### ISSUE TITLE
Add option to print formatted contents to stdout

### ISSUE THREAD

**Issue by ettom** [slomkowski/nginx-config-formatter#19]
Hi, this is a feature request for an option to print the formatted contents to stdout without saving them to a file. This would allow to use this program with formatting tools that work with stdin/stdout such as [vim-autoformat](https://github.com/Chiel92/vim-autoformat). The stdin can already be handled by passing `/dev/stdin` as the filename. Should be relatively simple to implement, if you want, I could whip up a pull request.

**Comment by slomkowski** [comment]
@ettom I welcome pull requests, merging my take time, because I have still #18 and #8 hanging because of conflicts and need for rewrite. However your feature should affect different area of code.

**Comment by slomkowski** [comment]
I implemented it, the option is `--print-result`  it will be merged to master soon. Do you have any suggestions?

**Comment by slomkowski** [comment]
Merged into master. I'd like to have some feedback before I create a release.

**Comment by ettom** [comment]
I tested it and it seems to work fine. Passing `/dev/stdin` as the filename won't work on Windows though. Perhaps a switch could be added to read the contents from stdin in a portable way?
So instead of this: `cat nginx.conf | nginxfmt.py -p /dev/stdin`
It would be this: `cat nginx.conf | nginxfmt.py -p --stdin`

It's not a problem for me personally, as I don't use Windows - just a thought.

**Comment by slomkowski** [comment]
OK, I think of following modes:

* format *n* files, backup if specified `nginxfmt file1.conf file2.conf ...`
* load *1* file from disk, display formatted content, cannot backup anything `nginxfmt -p file1.conf`
* read content from stdin, display formatted content `nginxfmt -` or `nginxfmt -p -`
* read content from stdin, save to *1* file `nginxfmt - output.conf`

Might be changed in case *argparse* doesn't support some syntax.

**Comment by ettom** [comment]
I tested the current solution and it seems to work fine, thanks!
