### ISSUE TITLE
No need special treatment for variable `${aaa}`

### ISSUE THREAD

**Issue by RickieL** [slomkowski/nginx-config-formatter#21]
No need special treatment for variable ${} , because any expression with "{"  should be enclosed in single or double quotes.

So, we just need to substitute `{` and `}` in   single or double quotes.

**Comment by RickieL** [comment]
There's a better solution, https://github.com/rwx------/nginxConfigFormatterGo

**Comment by slomkowski** [comment]
Can you verify that the current version (1.2.2) works OK?
